import { ReactElement, Suspense } from 'react';
import './globals.css';
import Link from 'next/link';
import { Switch } from "@/components";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactElement }>) {
  return (
    <html lang="en">
    <body>
    <Suspense>
      <Switch/>
    </Suspense>
    <ul>
      <li>
        <Link href="/">Go to /</Link>
      </li>
      <li>
        <Link href="/subpage">Go to /subpage</Link>
      </li>
      <li>
        <Link href="/client">Go to /client</Link>
      </li>
    </ul>
    {children}
    </body>
    </html>
  );
}
